#!/usr/bin/env bash
set -euo pipefail

api_base_url="${HEYBROSKI_API_BASE_URL:-http://localhost:8000}"

curl --fail --silent --show-error --max-time 10 "${api_base_url}/api/health" |
  python3 -c 'import json,sys; h=json.load(sys.stdin); print("Ollama:", h["services"]["ollama"], "| Model:", h["model"]); sys.exit(0 if h["services"]["ollama"] == "available" else 1)'

session_id="$(curl --fail --silent --show-error --max-time 10 -X POST "${api_base_url}/api/chat/sessions" |
  python3 -c 'import json,sys; print(json.load(sys.stdin)["session_id"])')"

curl --fail --silent --show-error --max-time 65 \
  -X POST "${api_base_url}/api/chat/sessions/${session_id}/messages" \
  -H 'Content-Type: application/json' \
  --data '{"message":"Who is waiting on me?"}' |
  python3 -c 'import json,sys; r=json.load(sys.stdin); print("Generated by:", r["generated_by"]); print(r["content"]); sys.exit(0 if r["generated_by"] == "ollama" else 1)'
